# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: /Users/isaac/Documents/GitHub/CrossViVit/example
sweep:
  dir: /Users/isaac/Documents/GitHub/CrossViVit/example
  subdir: ${hydra.job.num}